# encoding: utf-8
"""
@author: peng lei
@contact: me@penglei.com

@version: 1.0
@file: ccs_balance_sheet.py
@time: 2018/10/20 11:15

中概股
"""

from sqlalchemy import Column, String, Numeric, Date, Time, Integer,Text
from shannon_spider.db import CommonFieldMixin, ItemBaseModel


class CcsBalanceSheetItem(CommonFieldMixin, ItemBaseModel):
    '''中概股资产负债表抓取结果'''
    __tablename__ = 'ccs_balance_sheet'
    desc = '中概股资产负债表'
    DATETYPE = Column(String(40), doc={"zh": "日期类型"})
    CODE = Column(String(40), doc={"zh": "股票代码"})
    BBJZR = Column(String(40), doc={"zh": "日期"})
    CBLX = Column(String(40), doc={"zh": "财报类型"})
    NJR = Column(String(40), doc={"zh": "年结日"})
    BZ = Column(String(40), doc={"zh": "币种"})
    LDZC = Column(String(40), doc={"zh": "流动资产"})
    XJJXJDJW = Column(String(40), doc={"zh": "现金及现金等价物"})
    XZXXJJQTLD = Column(String(40), doc={"zh": "限制性现金及其他(流动)"})
    DQTZ = Column(String(40), doc={"zh": "短期投资"})
    YSZK = Column(String(40), doc={"zh": "应收账款"})
    YSGLFKX = Column(String(40), doc={"zh": "应收关联方款项"})
    YSPJLD = Column(String(40), doc={"zh": "应收票据(流动)"})
    YSSX = Column(String(40), doc={"zh": "应收税项"})
    CH = Column(String(40), doc={"zh": "存货"})
    DYSDSZCLD = Column(String(40), doc={"zh": "递延所得税资产(流动)"})
    CYZDQTZLD = Column(String(40), doc={"zh": "持有至到期投资(流动)"})
    KGCSTZLD = Column(String(40), doc={"zh": "可供出售投资(流动)"})
    YZZJYYWZC = Column(String(40), doc={"zh": "已终止经营业务资产"})
    YFKXLD = Column(String(40), doc={"zh": "预付款项(流动)"})
    QTLDZC = Column(String(40), doc={"zh": "其他流动资产"})
    QTYSK = Column(String(40), doc={"zh": "其他应收款"})
    YJZQTZLD = Column(String(40), doc={"zh": "有价证券投资(流动)"})
    CKLD = Column(String(40), doc={"zh": "存款(流动)"})
    LDZCQTXM = Column(String(40), doc={"zh": "流动资产其他项目"})
    LDZCHJ = Column(String(40), doc={"zh": "流动资产合计"})
    FLDZC = Column(String(40), doc={"zh": "非流动资产"})
    WYCFJSB = Column(String(40), doc={"zh": "物业、厂房及设备"})
    GDZC = Column(String(40), doc={"zh": "固定资产"})
    WXZC = Column(String(40), doc={"zh": "无形资产"})
    SY = Column(String(40), doc={"zh": "商誉"})
    TDSYQ = Column(String(40), doc={"zh": "土地使用权"})
    XZXXJJQTFLD = Column(String(40), doc={"zh": "限制性现金及其他(非流动)"})
    CQTZ = Column(String(40), doc={"zh": "长期投资"})
    YSPJFLD = Column(String(40), doc={"zh": "应收票据(非流动)"})
    DYSDSZCFLD = Column(String(40), doc={"zh": "递延所得税资产(非流动)"})
    CYZDQTZFLD = Column(String(40), doc={"zh": "持有至到期投资(非流动)"})
    KGCSTZFLD = Column(String(40), doc={"zh": "可供出售投资(非流动)"})
    QTTZ = Column(String(40), doc={"zh": "其他投资"})
    YFKXFLD = Column(String(40), doc={"zh": "预付款项(非流动)"})
    QTFLDZC = Column(String(40), doc={"zh": "其他非流动资产"})
    YJZQTZFLD = Column(String(40), doc={"zh": "有价证券投资(非流动)"})
    ZJGC = Column(String(40), doc={"zh": "在建工程"})
    CKFLD = Column(String(40), doc={"zh": "存款(非流动)"})
    QTCQYSK = Column(String(40), doc={"zh": "其他长期应收款"})
    FLDZCQTXM = Column(String(40), doc={"zh": "非流动资产其他项目"})
    FLDZCHJ = Column(String(40), doc={"zh": "非流动资产合计"})
    ZCQTXM = Column(String(40), doc={"zh": "资产其他项目"})
    ZZC = Column(String(40), doc={"zh": "总资产"})
    LDFZ = Column(String(40), doc={"zh": "流动负债"})
    YFZK = Column(String(40), doc={"zh": "应付账款"})
    YFGLFKXLD = Column(String(40), doc={"zh": "应付关联方款项(流动)"})
    YFPJLD = Column(String(40), doc={"zh": "应付票据(流动)"})
    YFSXLD = Column(String(40), doc={"zh": "应付税项(流动)"})
    YSJYTFY = Column(String(40), doc={"zh": "预收及预提费用"})
    QTYFKJYJFY = Column(String(40), doc={"zh": "其他应付款及应计费用"})
    DQZW = Column(String(40), doc={"zh": "短期债务"})
    CQFZBQBF = Column(String(40), doc={"zh": "长期负债(本期部分)"})
    YSGJFZLD = Column(String(40), doc={"zh": "衍生工具负债(流动)"})
    DYSRLD = Column(String(40), doc={"zh": "递延收入(流动)"})
    DYSDSFZLD = Column(String(40), doc={"zh": "递延所得税负债(流动)"})
    QTLDFZ = Column(String(40), doc={"zh": "其他流动负债"})
    KHCKJDK = Column(String(40), doc={"zh": "客户存款及垫款"})
    YFXCHFL = Column(String(40), doc={"zh": "应付薪酬和福利"})
    ZBZNZWLD = Column(String(40), doc={"zh": "资本租赁债务(流动)"})
    LDFZQTXM = Column(String(40), doc={"zh": "流动负债其他项目"})
    LDFZHJ = Column(String(40), doc={"zh": "流动负债合计"})
    FLDFZ = Column(String(40), doc={"zh": "非流动负债"})
    DYSDSFZFLD = Column(String(40), doc={"zh": "递延所得税负债(非流动)"})
    DYSRFLD = Column(String(40), doc={"zh": "递延收入(非流动)"})
    YFSXFLD = Column(String(40), doc={"zh": "应付税项(非流动)"})
    YFPJFLD = Column(String(40), doc={"zh": "应付票据(非流动)"})
    CQFZ = Column(String(40), doc={"zh": "长期负债"})
    KZHPJJZQ = Column(String(40), doc={"zh": "可转换票据及债券"})
    QTFLDFZ = Column(String(40), doc={"zh": "其他非流动负债"})
    YFGLFKXFLD = Column(String(40), doc={"zh": "应付关联方款项(非流动)"})
    QTCQYFK = Column(String(40), doc={"zh": "其他长期应付款"})
    YSGJFZFLD = Column(String(40), doc={"zh": "衍生工具负债(非流动)"})
    ZBZNZWFLD = Column(String(40), doc={"zh": "资本租赁债务(非流动)"})
    TXFLHGYQTBC = Column(String(40), doc={"zh": "退休福利和雇员其他补偿"})
    FLDFZQTXM = Column(String(40), doc={"zh": "非流动负债其他项目"})
    FLDFZHJ = Column(String(40), doc={"zh": "非流动负债合计"})
    FZQTXM = Column(String(40), doc={"zh": "负债其他项目"})
    ZFZ = Column(String(40), doc={"zh": "总负债"})
    ZBJCB = Column(String(40), doc={"zh": "资本及储备"})
    PTG = Column(String(40), doc={"zh": "普通股"})
    YXG = Column(String(40), doc={"zh": "优先股"})
    KCG = Column(String(40), doc={"zh": "库存股"})
    LCSY = Column(String(40), doc={"zh": "留存收益"})
    QTCB = Column(String(40), doc={"zh": "其他储备"})
    GBYJ = Column(String(40), doc={"zh": "股本溢价"})
    QTZHSY = Column(String(40), doc={"zh": "其他综合收益"})
    GSYMGSGDQYQTXM = Column(String(40), doc={"zh": "归属于母公司股东权益其他项目"})
    GSYMGSGDQY = Column(String(40), doc={"zh": "归属于母公司股东权益"})
    SSGDQY = Column(String(40), doc={"zh": "少数股东权益"})
    GDQYHJQTXM = Column(String(40), doc={"zh": "股东权益合计其他项目"})
    GDQYHJ = Column(String(40), doc={"zh": "股东权益合计"})
    FZJGDQYQTXM = Column(String(40), doc={"zh": "负债及股东权益其他项目"})
    FZJGDQYHJ = Column(String(40), doc={"zh": "负债及股东权益合计"})
    KJZZ = Column(String(40), doc={"zh": "会计准则"})